name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cc -o nob nob.c
          ./nob example
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest
      - name: build
        run: |
          cc -o nob nob.c
          ./nob example
